// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Image15;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Image12;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Panel2;
extern void ui_event_mic_switch1(lv_event_t * e);
extern lv_obj_t * ui_mic_switch1;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image4;
extern void ui_event_music_switch(lv_event_t * e);
extern lv_obj_t * ui_music_switch;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

