// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen3.h"
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_237439637);    // assets/icons8-mic-30.png
LV_IMG_DECLARE(ui_img_1771564824);    // assets/icons8-music-24.png
LV_IMG_DECLARE(ui_img_481835706);    // assets/icons8-micro-50.png
LV_IMG_DECLARE(ui_img_1424899605);    // assets/icons8-wireless-mic-53.png
LV_IMG_DECLARE(ui_img_1916212264);    // assets/icons8-bluetooth-50.png
LV_IMG_DECLARE(ui_img_461411260);    // assets/icons8-audio-mixer-58.png

// FONTS
LV_FONT_DECLARE(ui_font_Hebrew50);
LV_FONT_DECLARE(ui_font_Hebrew30);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
