// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void mic_V(lv_event_t * e)
{
	// Your code here
}

void music_V(lv_event_t * e)
{
	// Your code here
}

void mic_mode_toggle(lv_event_t * e)
{
	// Your code here
}

void main_Volume(lv_event_t * e)
{
	// Your code here
}
